import os

def generate(pid_file, log_file, log_level):
    pid_path = os.path.dirname(pid_file)
    if not log_file:
      log_file = "/dev/null"

    return """#!/bin/sh

# This file has been generated by Synoindex Watcher.

case "$1" in
  start|"")
    mkdir -p %s
    # Set LC_ALL to ensure that the filesystem encoding is correctly detected
    # during boot.
    nohup env LC_ALL=en_US.utf8 python -m synoindexwatcher \\
      --logfile %s \\
      --loglevel %s > /dev/null 2>&1 &
    echo $! > %s
    ;;
  restart|reload|force-reload)
    echo "Error: argument '$1' not supported" >&2
    exit 3
    ;;
  stop)
    kill `cat %s`
    ;;
  *)
    echo "Usage: synoindexwatcher.sh [start|stop]" >&2
    exit 3
    ;;
esac""" % (pid_path, log_file, log_level, pid_file, pid_file)
